# Generated by Django 4.1.7 on 2023-04-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_publishinghouse_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
        migrations.AlterModelTable(
            name='publishinghouse',
            table='PublishingHouse',
        ),
    ]
