# Generated by Django 4.1.7 on 2023-04-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_table_alter_book_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='Books',
        ),
    ]
