# Generated by Django 4.1.7 on 2023-04-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_books_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='blog_books',
        ),
    ]
