# Generated by Django 4.1.7 on 2023-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_book', models.IntegerField(primary_key=True, serialize=False)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'blog_books',
            },
        ),
    ]
